version: '3.1'

services:
  task-tracker-app:
    build: .
    depends_on:
      - task-tracker-app-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task-tracker-app-db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  task-tracker-app-db:
    image: postgres:14-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123